#!/usr/bin/env node

'use strict';

const path = require('path');

const FastBootServer = require('ember-alt-fastboot-app-server/src/backing-classes/cluster-master');
const serialize = require('ember-alt-fastboot-app-server/src/utils/serialization').serialize;

const config = {
  distPath: path.join(__dirname, '../'),
  host: '0.0.0.0',
  port: '4201',
  workerCount: 1,
  minifyHtml: true,
  buildSandboxGlobals(globalOptions) {
    return Object.assign({}, globalOptions, {
      process
    });
  }
};

const master = new FastBootServer(config);

master.start();
